import {chromium} from 'playwright';
import assert from 'node:assert/strict';

const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--enable-webgl']});
const page=await browser.newPage({viewport:{width:1280,height:800}});
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});
await page.goto('http://127.0.0.1:5188/?test=audio');
await page.waitForFunction(()=>window.__game&&document.body.dataset.nature==='loaded');
assert.equal(await page.evaluate(()=>__game.audio.context),null);
await page.click('#start');
await page.waitForFunction(()=>__game.audio.context?.state==='running');
const started=await page.evaluate(()=>({groups:[...__game.audio.buses.keys()],gain:__game.audio.master.gain.value,paused:__game.audio.paused}));
assert.deepEqual(started.groups,['sfx','ui','music','ambience','voice']);
assert.ok(Math.abs(started.gain-.8)<.001);
assert.equal(started.paused,false);
await page.evaluate(()=>__game.audio.playBossCue('charge','audio-test-owner'));
assert.equal(await page.evaluate(()=>__game.audio.voices.has('audio-test-owner')),true);
await page.click('#sound');
const muted=await page.evaluate(()=>({muted:__game.audio.muted,gain:__game.audio.master.gain.value,voices:__game.audio.voices.size}));
assert.equal(muted.muted,true);assert.equal(muted.gain,0);assert.ok(muted.voices<=1);
await page.click('#sound');
const unmuted=await page.evaluate(()=>({muted:__game.audio.muted,gain:__game.audio.master.gain.value}));
assert.equal(unmuted.muted,false);assert.ok(Math.abs(unmuted.gain-.8)<.001);
await page.click('#pause');
await page.waitForFunction(()=>__game.audio.context?.state==='suspended');
assert.equal(await page.evaluate(()=>__game.audio.paused),true);
await page.click('#resume');
await page.waitForFunction(()=>__game.audio.context?.state==='running');
assert.equal(await page.evaluate(()=>__game.audio.paused),false);
await page.evaluate(()=>__game.audio.stopAll());
assert.equal(await page.evaluate(()=>__game.audio.voices.size),0);
assert.deepEqual(errors,[]);
console.log('PASS: audio unlock, buses, immediate mute, pause/resume state, owner cleanup');
await browser.close();
