import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {WeaponCombat} from '../src/combat.js';
import {HEROES} from '../src/loadouts.js';

function setup(role,slot){
 const scene=new T.Scene(),hero=new T.Group(),state={damage:1,rate:1,shot:0},enemies=[],hits=[],pulses=[],links=[];
 hero.userData.profile=HEROES[role].weapons[slot];const garden={combos:new Set(),onShot(){},electrify(){},pulse(...args){pulses.push(args)}};
 const combat=new WeaponCombat({scene,hero,state,enemies:()=>enemies,garden,damage:(e,d,source)=>{e.hp-=d;hits.push({e,d,source});if(e.hp<=0)e.dead=true},effect:obj=>links.push(obj)});
 const enemy=(z,x=0,type='brute')=>{const obj=new T.Group();obj.position.set(x,0,z);const e={obj,size:.4,hp:1000,type,slow:0};enemies.push(e);return e};
 const step=t=>{for(let time=0;time<t;time+=.01)combat.step(Math.min(.01,t-time))};return {scene,combat,hero,state,enemies,hits,pulses,links,garden,enemy,step};
}
test('bow hits three enemies in spatial order only once each, with diminishing damage',()=>{const s=setup('Ranger',1);const far=s.enemy(8),near=s.enemy(3),middle=s.enemy(5),fourth=s.enemy(10);s.combat.attack();s.step(.5);assert.deepEqual(s.hits.map(h=>h.e),[near,middle,far]);assert.equal(near.hp,944);assert.ok(Math.abs(middle.hp-955.2)<1e-9);assert.ok(Math.abs(far.hp-964.16)<1e-9);assert.equal(fourth.hp,1000);assert.equal(s.combat.bullets.length,0)});
test('ordinary crossbow stops on the nearest target',()=>{const s=setup('Ranger',0),near=s.enemy(3),far=s.enemy(4);s.combat.attack();s.step(.3);assert.equal(near.hp,970);assert.equal(far.hp,1000)});
test('shotgun damages more at short distance; knockback resists on bosses and stays bounded',()=>{const fire=(z,type)=>{const s=setup('Engineer',0),e=s.enemy(z,0,type);s.combat.attack();s.step(.65);return {damage:1000-e.hp,push:e.obj.position.z-z}};const close=fire(2,'brute'),far=fire(9,'brute'),boss=fire(2,'boss');assert.ok(close.damage>far.damage);assert.ok(close.push>.5&&close.push<1);assert.ok(boss.push<close.push*.25)});
test('burst schedules three bolts, preserves damage snapshots and can cancel remaining rounds',()=>{const s=setup('Engineer',1);s.enemy(12);s.combat.attack();assert.equal(s.combat.bullets.length,1);assert.equal(s.combat.pending.length,2);s.state.damage=5;s.combat.step(.075);assert.equal(s.combat.bullets.length,2);assert.ok(s.combat.bullets.every(b=>b.damage===14));s.combat.step(.075);assert.equal(s.combat.bullets.length,3);assert.equal(s.combat.pending.length,0);s.combat.attack();const before=s.combat.bullets.length,cd=s.state.shot;s.combat.cancelBurst();s.combat.step(.1);assert.equal(s.combat.bullets.length,before);assert.equal(s.state.shot,cd)});
test('nature has a delayed stationary area, slows targets and allows escape',()=>{const s=setup('Druid',0),main=s.enemy(5),near=s.enemy(5,2),escape=s.enemy(5,-2),outside=s.enemy(5,3);s.combat.attack();s.combat.step(.24);assert.equal(main.hp,1000);escape.obj.position.x=-4;s.combat.cancelBurst();s.combat.step(.02);assert.equal(main.hp,958);assert.equal(near.hp,958);assert.equal(escape.hp,1000);assert.equal(outside.hp,1000);assert.equal(main.slow,1.4)});
test('lightning jumps from the previous enemy, never repeats, and honors jump distance',()=>{const s=setup('Druid',1),list=[2,5,8,11,16].map(z=>s.enemy(z));s.combat.attack();assert.equal(s.links.length,4);assert.deepEqual(s.hits.map(h=>h.e),list.slice(0,4));assert.ok(Math.abs(list[3].hp-(1000-30*.8**3))<1e-9);assert.equal(list[4].hp,1000)});
test('magic orb has travel time, direct damage and reduced splash without double hitting',()=>{const s=setup('Druid',2),main=s.enemy(5),near=s.enemy(5,1),outside=s.enemy(5,2);s.combat.attack();assert.equal(main.hp,1000);s.step(.4);assert.equal(main.hp,954);assert.ok(Math.abs(near.hp-981.6)<1e-9);assert.equal(outside.hp,1000);assert.equal(s.hits.filter(h=>h.e===main).length,1)});
test('pending attacks and projectiles are cleared on reset; stunned enemies cannot absorb shots',()=>{const s=setup('Engineer',1),a=s.enemy(2),b=s.enemy(4);a.stunned=true;s.combat.attack();s.step(.2);assert.equal(a.hp,1000);assert.ok(b.hp<1000);s.combat.reset();assert.equal(s.combat.pending.length,0);assert.equal(s.combat.bullets.length,0);assert.equal(s.scene.children.length,0)});
test('electric combo applies to chain lightning but not nature or magic orb',()=>{for(const slot of [0,1,2]){const s=setup('Druid',slot),e=s.enemy(3);e.slow=2;s.garden.combos.add('snare');s.combat.attack();s.step(.4);const expected=s.hero.userData.profile.damage*(slot===1?1.7:1);assert.ok(Math.abs(e.hp-(1000-expected))<1e-9)}});
test('melee has real windup and a front cone; rear and out-of-range enemies are excluded',()=>{const s=setup('Knight',0),front=s.enemy(2),side=s.enemy(1,2),rear=s.enemy(-2.5),far=s.enemy(4);s.combat.attack();s.combat.step(.17);assert.equal(front.hp,1000);s.combat.step(.02);assert.equal(front.hp,962);assert.equal(side.hp,1000);assert.equal(rear.hp,1000);assert.equal(far.hp,1000);assert.equal(s.combat.bullets.length,0)});
test('switch cancels uncommitted melee, while moving out of its reach avoids the hit',()=>{const s=setup('Knight',1),e=s.enemy(3);s.combat.attack();s.combat.cancelBurst();s.step(.5);assert.equal(e.hp,1000);s.combat.attack();e.obj.position.z=5;s.step(.5);assert.equal(e.hp,1000)});
test('mace staggers ordinary enemies with reduced boss duration',()=>{const s=setup('Knight',2),e=s.enemy(2),boss=s.enemy(2,.4,'boss');s.combat.attack();s.step(.3);assert.equal(e.hp,948);assert.equal(e.stagger,.45);assert.ok(Math.abs(boss.stagger-.09)<1e-9)});
