import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {Garden,COMBOS} from '../src/garden.js';
function setup(){const scene=new T.Scene(),hero=new T.Group(),state={hp:40,maxHp:100,damage:1,time:0,weapon:0},enemies=[];scene.add(hero);let garden;garden=new Garden({scene,hero,state,visualFactory:()=>new T.Group(),random:()=>0,enemies:()=>enemies,damage:(e,d,source)=>{e.hp-=d;if(e.hp<=0&&!e.dead){e.dead=true;garden.onKill(e.obj.position,source)}},toast:()=>{},burst:()=>{}});const enemy=(x=2,hp=300)=>{const obj=new T.Group();obj.position.x=x;const e={obj,hp,dead:false};enemies.push(e);return e};return {garden,hero,state,enemy,enemies,scene}}
test('weapon-attributed seeds collect into matching plants; nonweapon kills do not multiply seeds',()=>{const {garden,hero}=setup();for(let w=0;w<3;w++)garden.onKill(hero.position,{weapon:w});garden.onKill(hero.position,{garden:true});assert.equal(garden.seeds.length,3);garden.step(.1,[],()=>{});assert.deepEqual(garden.plants.map(p=>p.type),[0,1,2]);assert.equal(garden.seeds.length,0);});
test('all three plants mature and damage nearby enemies; pumpkin is consumed',()=>{for(let type=0;type<3;type++){const {garden,hero,enemy}=setup();const e=enemy();garden.plant(type,hero.position);garden.step(1.2,[],()=>{});assert.ok(e.hp<300);if(type===1)assert.equal(garden.plants.length,0)}});
test('voltage detonates pumpkins and sends up to three distant followup hits',()=>{const {garden,hero,enemy}=setup();const e=enemy(7);garden.combos.add('voltage');const p=garden.plant(1,hero.position);garden.electrify(hero.position);assert.equal(p.dead,true);assert.equal(e.hp,274);assert.equal(garden.stats.combos,1)});
test('thorn slow amplifies electric damage',()=>{const {garden,hero,enemy}=setup();const e=enemy();garden.combos.add('snare');garden.hit(e,10,'thorn',hero.position);assert.equal(e.slow,2.5);garden.hit(e,10,'electric',hero.position);assert.equal(e.hp,273)});
test('compost heals and extends surrounding plant life on plant kill',()=>{const {garden,hero,enemy,state}=setup();garden.combos.add('compost');const p=garden.plant(0,hero.position);const e=enemy(2,5);garden.hit(e,10,'thorn',hero.position);assert.equal(state.hp,42);assert.equal(p.life,51)});
test('shotgun waters but other weapons do not',()=>{const {garden,hero}=setup();garden.combos.add('watering');const p=garden.plant(0,hero.position);garden.onShot(0);assert.ok(p.grow>0);garden.onShot(1);assert.equal(p.grow,0);assert.equal(p.cooldown,0);assert.ok(p.life>48)});
test('dash plants two matching crops',()=>{const {garden,state}=setup();garden.combos.add('pollen');state.weapon=2;garden.onDash(new T.Vector3(),new T.Vector3(5,0,0));assert.deepEqual(garden.plants.map(p=>p.type),[2,2]);});
test('companions collect, heal, and friendship multiplies nearby plant damage',()=>{const {garden,hero,enemy,state}=setup();garden.recruit('slime');garden.recruit('mushroom');garden.combos.add('friendship');const e=enemy();garden.hit(e,20,'thorn',hero.position);assert.equal(e.hp,270);const drop={obj:new T.Group()};drop.obj.position.set(-5,.5,0);const before=drop.obj.position.distanceTo(hero.position);garden.step(4.1,[drop],()=>{});assert.equal(state.hp,48);assert.ok(drop.obj.position.distanceTo(hero.position)<before);garden.recruit('slime');assert.equal(garden.buddies.length,2);assert.equal(garden.buddies[0].rank,2)});
test('boss warning waits before damaging player and destroying plants',()=>{const {garden,hero}=setup();const p=garden.plant(0,hero.position);let damage=0;garden.stomp(hero.position);garden.step(.8,[],d=>damage+=d);assert.equal(damage,0);assert.equal(p.dead,false);garden.step(.81,[],d=>damage+=d);assert.equal(damage,28);assert.equal(p.dead,true);assert.equal(garden.stats.destroyed,1)});
test('caps, expiration and restart keep garden objects bounded',()=>{const {garden,hero,scene}=setup();for(let i=0;i<60;i++){garden.plant(i%3,hero.position);garden.seed(i%3,new T.Vector3(15,0,0))}assert.equal(garden.plants.length,24);assert.equal(garden.seeds.length,36);garden.combos.add(COMBO_ID());garden.reset();assert.equal(scene.children.length,1);assert.equal(garden.plants.length,0);assert.equal(garden.combos.size,0)});
function COMBO_ID(){return COMBOS[0].id}
test('dead or removed stomp source cannot hurt player or destroy plants',()=>{for(const removed of [false,true]){const {garden,hero,enemy,enemies}=setup();const boss=enemy(20),plant=garden.plant(0,hero.position);let damage=0;garden.stomp(hero.position,boss);garden.step(.8,[],d=>damage+=d);if(removed)enemies.splice(0);else boss.dead=true;garden.step(.81,[],d=>damage+=d);assert.equal(damage,0);assert.equal(plant.dead,false);assert.equal(garden.stats.destroyed,0);assert.equal(garden.effects.filter(f=>f.stomp).length,0)}});
test('stomp cancellation is scoped to its caster and removes scene object',()=>{const {garden,hero,enemy,scene}=setup();const first=enemy(20),second=enemy(21);garden.stomp(hero.position,first);const cancelled=garden.effects.at(-1).obj;garden.stomp(hero.position,second);garden.pulse(hero.position,0,1);garden.cancelStomps(first);assert.equal(scene.children.includes(cancelled),false);assert.equal(garden.effects.length,2);assert.equal(garden.effects.find(f=>f.stomp).source,second);let damage=0;garden.step(1.61,[],d=>damage+=d);assert.equal(damage,28)});
test('each weapon family can supply all three device types with 60/20/20 thresholds',()=>{for(let weapon=0;weapon<3;weapon++){const {garden,hero}=setup();for(const value of [.1,.59,.6,.79,.8,.99]){garden.random=()=>value;garden.onKill(hero.position,{weapon})}assert.deepEqual(garden.seeds.map(s=>s.type),[weapon,weapon,(weapon+1)%3,(weapon+1)%3,(weapon+2)%3,(weapon+2)%3])}});
