import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type())&&!m.text().includes('GPU stall'))errors.push(m.text())});
 await page.goto('http://127.0.0.1:5188/?test=1');await page.waitForFunction(()=>window.__game&&document.body.dataset.nature==='loaded');await page.click('[data-character="Knight"]');await page.click('#start');
 const defense=await page.evaluate(()=>{const g=__game;g.state.mode='paused';g.equip(0);g.state.hp=100;g.state.inv=0;g.hurt(10);const shield=g.state.hp;g.equip(1);g.state.inv=0;g.hurt(10);return {shield,noShield:g.state.hp,offhand:g.hero.userData.rig.offhand.children.length}});assert.deepEqual(defense,{shield:92,noShield:82,offhand:0});
 const interrupt=await page.evaluate(()=>{const g=__game;g.state.mode='paused';g.equip(2);g.state.inv=999;g.state.remaining=1;g.state.spawn=999;g.hero.position.set(0,0,0);g.spawnEnemy('spitter');const e=g.enemies.at(-1);e.obj.position.set(0,0,2);e.hp=1000;e.attack=.05;g.attack();g.combat.step(.26);const position=e.obj.position.clone();g.state.shot=999;g.state.mode='playing';g.tick(.1);g.state.mode='paused';return {stagger:e.stagger,moved:e.obj.position.distanceTo(position),shots:g.hazards.length,attack:e.attack,statusVisible:e.statusVfx.stagger.visible}});assert.ok(interrupt.stagger>0);assert.equal(interrupt.moved,0);assert.equal(interrupt.shots,0);assert.equal(interrupt.attack,.05);assert.equal(interrupt.statusVisible,true);
 const slowStatus=await page.evaluate(()=>{const g=__game,e=g.enemies.at(-1);e.stagger=0;e.slow=1.4;g.state.mode='playing';g.tick(.1);g.state.mode='paused';return {slow:e.slow,visible:e.statusVfx.slow.visible,staggerVisible:e.statusVfx.stagger.visible}});assert.ok(slowStatus.slow>1);assert.equal(slowStatus.visible,true);assert.equal(slowStatus.staggerVisible,false);
 const feedback=await page.evaluate(()=>{const g=__game,calls=[];g.audio.playMeleeImpact=(...args)=>calls.push(args);const result=[];for(let slot=0;slot<3;slot++){g.equip(slot);const e=g.enemies.at(-1);e.dead=false;e.stunned=false;e.stagger=0;e.hitStop=0;e.hp=10000;e.obj.position.set(0,0,2);g.state.shot=0;g.attack();g.combat.step(g.hero.userData.profile.delay+.01);result.push({...g.lastMeleeFeedback,targetFreeze:e.hitStop});}return {result,calls}});assert.deepEqual(feedback.result.map(item=>item.model),['sword_1handed','sword_2handed','Skeleton_Mace']);assert.ok(feedback.result.every(item=>item.hits===1&&item.targetFreeze>0));assert.ok(feedback.result[1].freeze>feedback.result[0].freeze);assert.ok(feedback.result[1].shake>feedback.result[2].shake&&feedback.result[2].shake>feedback.result[0].shake);assert.equal(feedback.calls.length,3);
 const poses=await page.evaluate(()=>{const g=__game,A=g.actors,T=g.THREE,scene=new T.Scene(),poses=[];scene.background=new T.Color(0x263b43);scene.add(new T.HemisphereLight(0xd3edf3,0x445040,2));const light=new T.DirectionalLight(0xffe8c7,2);light.position.set(4,9,6);scene.add(light);for(let slot=0;slot<3;slot++)for(let phase=0;phase<3;phase++){const {hero}=A.createHero(scene);A.selectHero(hero,'Knight');A.equipActor(hero,slot);hero.position.set((slot-1)*3.6,0,(phase-1)*3.6);A.animateActor(hero,.1,0,0);const before=hero.userData.rig.arms[1].quaternion.toArray();if(phase){A.kickActor(hero);A.animateActor(hero,phase===1?hero.userData.profile.delay:.08,1,phase===2?6:0)}const r=hero.userData.rig;poses.push({slot,phase,clip:r.attackClip,layered:r.layered,before,after:r.arms[1].quaternion.toArray(),shield:r.offhand.children.length,tracks:r.attackAction?.getClip().tracks.map(t=>t.name)})}const camera=new T.OrthographicCamera(-7,7,4.375,-4.375,.1,100);camera.position.set(4,11,19);camera.lookAt(0,1,0);const renderer=new T.WebGLRenderer({antialias:true});renderer.setSize(1440,900);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;Object.assign(renderer.domElement.style,{position:'fixed',inset:0,zIndex:9999});document.body.append(renderer.domElement);renderer.render(scene,camera);return poses});
 for(const p of poses){assert.ok(p.layered);assert.equal(p.shield,p.slot===0?1:0);if(p.phase){assert.ok(p.clip.startsWith('Melee_'));assert.notDeepEqual(p.before,p.after);assert.ok(!p.tracks.some(t=>/upperleg|lowerleg|root|hips/.test(t)))}}
 await page.screenshot({path:'test-results/knight-combat.png'});assert.deepEqual(errors,[]);await writeFile('test-results/knight-combat.json',JSON.stringify({passed:true,defense,interrupt,poses,errors},null,2));console.log('PASS: real melee clips, upper-body layering, shield defense, shield removal, mace interrupt, no browser warnings');
}finally{await browser.close()}
