from pathlib import Path
p=Path('src/main.js')
s=p.read_text(encoding='utf-8-sig')
s=s.replace("import {createWorld,createHero,createCreature,createPickup,loadNatureAssets,animateActor,kickActor} from './apocalypse.js';", "import {createPickup} from './apocalypse.js';\nimport {createWorld,loadNatureAssets} from './ruins.js';\nimport {preloadActors,createHero,createCreature,animateActor,kickActor,equipActor,selectHero,hitActor,dieActor,resetActor,disposeActor} from './actors.js';")
s=s.replace("let best=0;", "async function boot(){\nconst startButton=$('#start');startButton.disabled=true;\nfor(;;){try{await preloadActors((n,total)=>{startButton.textContent=`准备冒险者与动作 ${n} / ${total}`});break}catch(error){console.error(error);startButton.textContent='素材加载失败 · 点击重试';startButton.disabled=false;await new Promise(resolve=>startButton.onclick=resolve);startButton.disabled=true}}\nstartButton.disabled=false;startButton.textContent='进入遗迹　 →';document.body.dataset.actors='loaded';\nlet best=0;")
s=s.replace('const {hero,legs,held}=createHero(scene);','const {hero}=createHero(scene);')
a=s.index('function equip(){');b=s.index('\nring(.8',a)
s=s[:a]+"function equip(){equipActor(hero,state.weapon);document.querySelectorAll('.weapon').forEach((b,i)=>b.classList.toggle('active',i===state.weapon))}"+s[b:]
s=s.replace('let enemies=[],bullets=[],drops=[],fx=[],hazards=[]','let enemies=[],bullets=[],drops=[],fx=[],hazards=[],corpses=[]')
s=s.replace('scene.remove(x.obj);if(x.dispose)', 'if(x.obj.userData.rig)disposeActor(x.obj);else scene.remove(x.obj);if(x.dispose)')
s=s.replace('[enemies,bullets,drops,fx,hazards].forEach', '[enemies,bullets,drops,fx,hazards,corpses].forEach')
s=s.replace('hero.userData.rig.phase=0;hero.userData.rig.kick=0;', 'resetActor(hero);')
s=s.replace('const g=createCreature(type);', "const g=createCreature(elite&&type==='brute'?'necromancer':type);")
s=s.replace('e.hp-=d;burst', 'e.hp-=d;hitActor(e.obj);burst')
s=s.replace('scene.remove(e.obj);burst(e.obj.position);', 'dieActor(e.obj);corpses.push({obj:e.obj,life:1.6});burst(e.obj.position);')
s=s.replace('e.dead=true;scene.remove(e.obj);pendingElite', 'e.dead=true;disposeActor(e.obj);pendingElite')
s=s.replace('state.hp=Math.max(0,state.hp-amount);', 'state.hp=Math.max(0,state.hp-amount);hitActor(hero);')
s=s.replace("state.mode=win?'won':'lost';", "state.mode=win?'won':'lost';if(!win)dieActor(hero);")
s=s.replace("if(state.weapon===3)held.rotation.z=-.35+hero.userData.rig.kick*1.6;else held.rotation.z=0;", '')
s=s.replace("if(distance<e.size+.45)hurt(e.type==='boss'?22:9);", "if(distance<e.size+.45){hurt(e.type==='boss'?22:9);if(e.attack<=0){kickActor(e.obj);e.attack=.8}}")
s=s.replace("if(state.mode==='playing')tick(dt);if(state.mode", "if(state.mode==='playing')tick(dt);if(state.mode==='lost')animateActor(hero,dt,now/1000,0);if(['playing','won','lost'].includes(state.mode)){for(const c of corpses){c.life-=dt;animateActor(c.obj,dt,now/1000,0);if(c.life<.35)c.obj.position.y-=dt*3}corpses=corpses.filter(c=>{if(c.life<=0){disposeActor(c.obj);return false}return true})}if(state.mode")
s=s.replace('attack,tick,damageEnemy', 'get corpses(){return corpses},selectHero,equip,attack,tick,damageEnemy')
s=s.replace("$('#start').onclick=start;", "$('#start').onclick=start;document.querySelectorAll('[data-character]').forEach(b=>b.onclick=()=>{selectHero(hero,b.dataset.character);document.querySelectorAll('[data-character]').forEach(x=>x.classList.toggle('selected',x===b))});")
s=s.replace('<button id="start" class="primary">', '<div id="characters" aria-label="选择冒险者">'+''.join(f'<button data-character="{name}" class="'+('selected' if i==0 else '')+f'">{label}</button>' for i,(name,label) in enumerate([('Ranger','游侠'),('Knight','骑士'),('Druid','德鲁伊'),('Engineer','工程师')]))+'</div><button id="start" class="primary">')
replacements={'末日苗圃':'遗迹花园','DEADLAND NURSERY':'RELIC GARDEN','末日<br>苗圃':'遗迹<br>花园','用刀、弩或枪清除感染者，收集种子，在废墟重建防线。':'挥剑、射弩、施法，击退骸骨军团，在遗迹种下防线。','击破感染精英，修复救援设备，守住最后的苗圃。':'击败亡灵精英，唤醒守护构装体，守住遗迹花园。','重装变异体':'骸骨巨像','感染潮来袭':'骸骨军团来袭','进入隔离区':'进入遗迹','隔离区已肃清':'遗迹已守住','最后的苗圃得以保存':'遗迹花园得以保存','电磁发射器':'雷鸣法杖','锯齿长刀':'守卫长剑','电磁武器':'雷鸣法杖','电磁变异花':'雷光花','拾荒机器人':'采集构装体','医疗无人机':'治愈构装体','拾荒机':'采集构装体','医疗机':'治愈构装体','发现救援设备':'唤醒遗迹守卫','修复携带的救援设备':'唤醒封印中的构装体','修复 ·':'唤醒 ·','战地改装':'遗迹祝福','强力弹药':'锋芒祝福','敏捷扳机':'迅捷祝福','破门霰弹':'炼金霰弹'}
for old,new in replacements.items():s=s.replace(old,new)
s+='\n}\nboot().catch(error=>{console.error(error);const button=document.querySelector("#start");button.disabled=false;button.textContent="启动失败 · 点击重新加载";button.onclick=()=>location.reload()});\n'
p.write_text(s,encoding='utf-8')
p=Path('index.html');s=p.read_text(encoding='utf-8-sig').replace('末日苗圃 · Battle Garden','遗迹花园 · Relic Garden');p.write_text(s,encoding='utf-8')
