import * as T from 'three';
import * as Actors from './actors.js';
import {HEROES} from './loadouts.js';
import './style.css';
import './apocalypse.css';
import {projectile} from './projectiles.js';
import {WeaponCombat} from './combat.js';
import {Garden,COMBOS,PLANTS} from './garden.js';
import {createWorld,loadNatureAssets,createPickup} from './ruins.js';
import {preloadActors,createHero,createCreature,animateActor,kickActor,equipActor,selectHero,hitActor,dieActor,resetActor,disposeActor} from './actors.js';
const $=s=>document.querySelector(s), app=$('#app');
const icons=[`<path d="M4 21L19 6M14 4l6-2-2 6M3 16l5 5"/>`,`<path d="M4 20L18 6M12 3l9 9M5 9l10 10M4 20l5-1-4-4z"/>`,`<path d="M4 21L15 10M15 2l7 7-7 4-4-4z"/>`];
app.innerHTML=`<div id="xp"></div><header id="hud"><div><div class="eyebrow">RELIC WORKSHOP</div><div class="brand">遗迹工坊</div><div class="hp"><i id="health"></i></div><small id="healthtext">100 / 100</small></div><div class="readout"><div>第 <strong id="wave">01</strong> 波 / 08</div><div><span id="time">00:00</span> · 击败 <span id="kills">0</span> · LV <span id="level">1</span></div><button id="sound" aria-label="开关音效">音效 开</button><button id="pause" aria-label="暂停">Ⅱ</button></div></header><div id="bossbar" class="hidden">骸骨巨像<div><i></i></div></div><div id="toast"></div><aside id="garden-hud"><b>我的战场装置</b><div id="garden-counts"></div><div id="buddy-list">伙伴：第 2 波起，精英残血可收服</div><div id="combo-list">击杀掉战利品 · 靠近收集后自动部署</div><button id="guide">玩法图鉴 ?</button></aside><div id="bottom"><div id="weapons"></div><div id="controls">W A S D / 方向键 移动 · SPACE 冲刺<br>自动瞄准攻击 · 1 / 2 / 3 切换武器 · ESC 暂停<br><span id="dashstatus">冲刺就绪</span></div><button id="touchdash" class="primary">冲刺</button></div><div id="touch">${['↑','←','↓','→'].map((s,i)=>`<button data-key="${['w','a','s','d'][i]}">${s}</button>`).join('')}</div><section id="overlay"><div class="cover"><div class="seal">3D SURVIVAL ROGUELITE</div><h1>遗迹<br>工坊<span>RELIC WORKSHOP</span></h1><p>射弩、开火、施法，击退骸骨军团，用战利品构筑防线。<br>自动弩台 × 炼金炸瓶 × 雷鸣法典，组合产生连锁反应。<br>击败亡灵精英，唤醒守护构装体，守住遗迹工坊。</p><div id="characters" aria-label="选择冒险者"><button data-character="Ranger" class="selected">游侠</button><button data-character="Knight">骑士</button><button data-character="Druid" class="">德鲁伊</button><button data-character="Engineer" class="">工程师</button></div><p id="role-description"></p><button id="start" class="primary">进入遗迹　 →</button><footer>轻松开局 · 越战越强 · <span id="best"></span></footer></div></section><section id="modal" class="hidden"></section>`;
async function boot(){
const startButton=$('#start');startButton.disabled=true;
for(;;){try{await preloadActors((n,total)=>{startButton.textContent=`准备角色、动作与道具 ${n} / ${total}`});break}catch(error){console.error(error);startButton.textContent='素材加载失败 · 点击重试';startButton.disabled=false;await new Promise(resolve=>startButton.onclick=resolve);startButton.disabled=true}}
startButton.disabled=false;startButton.textContent='进入遗迹　 →';document.body.dataset.actors='loaded';
let best=0;try{best=Number(localStorage.getItem('ember-best'))||0}catch{}$('#best').textContent=`最佳 ${best} 击败`;
const scene=new T.Scene();scene.background=new T.Color('#a5dcf0');
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;app.prepend(renderer.domElement);
const camera=new T.PerspectiveCamera(42,innerWidth/innerHeight,.1,110);camera.position.set(20,24,27);camera.lookAt(0,0,0);
scene.add(new T.HemisphereLight(0xb9e5dc,0x26313b,2.2));const sun=new T.DirectionalLight(0xc7e7da,2.5);sun.position.set(-12,24,10);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-25,right:25,top:25,bottom:-25,far:70});sun.shadow.bias=-.001;scene.add(sun);
const mats={stone:new T.MeshStandardMaterial({color:0x425655,roughness:1,flatShading:true}),dark:new T.MeshStandardMaterial({color:0x233b3c,roughness:1}),gold:new T.MeshStandardMaterial({color:0xd7ae66,metalness:.5,roughness:.4}),cloth:new T.MeshStandardMaterial({color:0xd67848,roughness:1,flatShading:true}),skin:new T.MeshStandardMaterial({color:0xd9cba5,roughness:.85}),glow:new T.MeshBasicMaterial({color:0xffc77e}),green:new T.MeshStandardMaterial({color:0x4b715c,roughness:1,flatShading:true}),enemy:new T.MeshStandardMaterial({color:0x755469,roughness:.8,flatShading:true}),red:new T.MeshBasicMaterial({color:0xff866c})};
const geo={orb:new T.IcosahedronGeometry(1,0),box:new T.BoxGeometry(1,1,1),cyl:new T.CylinderGeometry(1,1,1,8),cone:new T.ConeGeometry(1,1,7)};
function mesh(g,m,x=0,y=0,z=0,sx=1,sy=sx,sz=sx,parent=scene){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function ring(r,width,color,parent=scene){const o=new T.Mesh(new T.RingGeometry(r-width,r,80),new T.MeshBasicMaterial({color,transparent:true,opacity:.65,side:T.DoubleSide}));o.rotation.x=-Math.PI/2;o.position.y=.035;parent.add(o);return o}
const {flame}=createWorld(scene);
const {hero}=createHero(scene);
function equip(slot=state.loadout){
  const previous=state.loadout;if(!equipActor(hero,slot))return;if(previous!==slot)combat.cancelBurst();
  state.loadout=slot;state.weapon=hero.userData.weapon;
  const role=HEROES[hero.userData.rig.name];
  $('#weapons').innerHTML=role.weapons.map((w,i)=>`<button class="weapon ${i===slot?'active':''}" data-weapon="${i}" title="${w.detail}"><small>${role.label} / 0${i+1}</small><b>${w.label}</b><span class="weapon-detail">${w.detail}</span></button>`).join('');
  $('#role-description').textContent=`${role.label} · ${role.description}。${role.weapons.map(w=>w.label).join(' / ')}，局内按 ${role.weapons.map((_,i)=>i+1).join(' / ')} 切换。`;
  document.querySelectorAll('[data-weapon]').forEach(b=>b.onclick=()=>{if(['title','playing','paused'].includes(state.mode))equip(+b.dataset.weapon)});
}
function chooseHero(name){if(state.mode!=='title'||!selectHero(hero,name))return false;state.loadout=0;equip();document.querySelectorAll('[data-character]').forEach(b=>b.classList.toggle('selected',b.dataset.character===name));return true}
function returnToTitle(){combat.reset();garden.reset();pendingElite=null;[enemies,drops,fx,hazards,corpses].forEach(clearObjects);keys.clear();resetActor(hero);state.mode='title';$('#modal').classList.add('hidden');$('#overlay').classList.remove('hidden');equip()}

ring(.8,.05,0xffffff,hero);
const state={mode:'title',loadout:0,hp:100,maxHp:100,wave:1,kills:0,level:1,xp:0,need:7,time:0,weapon:0,damage:1,rate:1,speed:6,magnet:3,dash:0,inv:0,shot:0,waveTime:0,spawn:0,remaining:0};let enemies=[],drops=[],fx=[],hazards=[],corpses=[];const keys=new Set();let lastDir=new T.Vector3(0,0,1),toastTime=0,audioCtx,muted=false;
function sound(f=300,d=.06,type='sine',volume=.025){if(muted)return;try{audioCtx??=new AudioContext();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(f,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(f*.5,audioCtx.currentTime+d);g.gain.setValueAtTime(volume,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch{}}
function toast(s){$('#toast').textContent=s;toastTime=3}
function clearObjects(list){for(const x of list){if(x.obj.userData.rig)disposeActor(x.obj);else scene.remove(x.obj);if(x.dispose){x.obj.geometry.dispose();x.obj.material.dispose()}}list.length=0}
function start(){combat.reset();keys.clear();lastDir.set(0,0,1);garden.reset();pendingElite=null;[enemies,drops,fx,hazards,corpses].forEach(clearObjects);Object.assign(state,{mode:'playing',hp:100,maxHp:100,wave:1,kills:0,level:1,xp:0,need:7,time:0,weapon:0,damage:1,rate:1,speed:6,magnet:3,dash:0,inv:0,shot:0});hero.position.set(0,0,4);resetActor(hero);$('#overlay').classList.add('hidden');$('#modal').classList.add('hidden');equip();beginWave();sound(500,.2)}
function beginWave(){state.remaining=state.wave===8?8:6+state.wave*3;state.spawn=.6;state.waveTime=0;if([2,4,6].includes(state.wave))spawnEnemy(state.wave===4?'runner':'brute',true);toast(state.wave===8?'最后的挑战 · 骸骨巨像':`第 ${state.wave} 波 · 骸骨军团来袭`);if(state.wave===8)spawnEnemy('boss')}
function spawnEnemy(force,elite=false){let type=force||(state.wave>2&&Math.random()<.23?'spitter':Math.random()<.3?'runner':'brute');const a=Math.random()*Math.PI*2;const g=createCreature(elite&&type==='brute'?'necromancer':type);g.position.set(Math.cos(a)*20,0,Math.sin(a)*20);scene.add(g);let size=type==='boss'?2.1:type==='runner'?.6:.85;if(elite){g.scale.multiplyScalar(1.35);const crown=mesh(geo.cone,mats.gold,0,type==='runner'?1.6:1.8,0,.35,.45,.35,g);crown.rotation.z=.15}const hp=elite?150+state.wave*15:type==='boss'?1500:type==='runner'?25:45+state.wave*5;enemies.push({obj:g,type,elite,stunned:false,slow:0,hp,maxHp:hp,size,speed:type==='boss'?1.1:type==='runner'?3.5:1.6+state.wave*.06,attack:1.5});}
function burst(pos,color=0xfbc47b,n=8){for(let i=0;i<n&&fx.length<180;i++){const o=mesh(geo.orb,color===0xfbc47b?mats.glow:mats.red,pos.x,.7,pos.z,.07);fx.push({obj:o,life:.4+Math.random()*.3,v:new T.Vector3((Math.random()-.5)*6,Math.random()*5,(Math.random()-.5)*6)})}}
function damageEnemy(e,d,source={}){if(e.dead||e.stunned)return;e.hp-=d;hitActor(e.obj);burst(e.obj.position,0xfbc47b,3);if(e.elite&&e.hp<=e.maxHp*.3){e.hp=Math.max(1,e.hp);e.stunned=true;pendingElite=e;return}if(e.hp<=0){e.dead=true;state.kills++;garden.onKill(e.obj.position,source);sound(140,.07,'triangle',.012);const obj=createPickup(scene,e.obj.position);drops.push({obj,value:e.type==='boss'?15:e.type==='brute'?2:1});if(Math.random()<.09){const obj=createPickup(scene,e.obj.position,true);drops.push({obj,value:0,heal:true})}dieActor(e.obj);corpses.push({obj:e.obj,life:1.6});burst(e.obj.position);}}
let pendingElite=null;
const garden=new Garden({scene,hero,state,enemies:()=>enemies,damage:damageEnemy,toast,burst});
const combat=new WeaponCombat({scene,hero,state,enemies:()=>enemies,damage:damageEnemy,garden,onFire:profile=>{kickActor(hero,state.rate);sound([600,180,850,240][profile.type],.07,profile.type===1?'sawtooth':'triangle',.018)},effect:(obj,life)=>{if(fx.length>=180)return;scene.add(obj);fx.push({obj,life,v:new T.Vector3(),fixed:true})}});
function captureChoice(){const e=pendingElite;if(!e)return;state.mode='capture';keys.clear();const type=e.type==='runner'?'mushroom':'slime',name=type==='slime'?'采集构装体':'治愈构装体';$('#modal').innerHTML=`<div class="eyebrow">SALVAGE PROTOCOL</div><h2>唤醒遗迹守卫</h2><p>精英失去战斗能力：唤醒封印中的构装体，或回收材料强化武器。战斗已暂停。</p><div id="choices"><button class="card" id="recruit"><div class="symbol">♥</div><h3>唤醒 · ${name}</h3><p>${type==='slime'?'帮助收集经验和战利品。已有同类时提升伙伴等级。':'每 4 秒治疗并充能维护附近装置。已有同类时提升伙伴等级。'}</p></button><button class="card" id="harvest"><div class="symbol">✦</div><h3>获取成长</h3><p>击败精英，立即获得一次三选一升级。</p></button></div>`;$('#modal').classList.remove('hidden');function resolve(){e.dead=true;disposeActor(e.obj);pendingElite=null;state.mode='playing';$('#modal').classList.add('hidden')}$('#recruit').onclick=()=>{resolve();garden.recruit(type)};$('#harvest').onclick=()=>{resolve();state.kills++;state.xp+=state.need;levelUp()}}
function attack(){return combat.attack()}
function hurt(amount){if(state.inv>0)return;amount*=hero.userData.profile.damageTaken||1;state.hp=Math.max(0,state.hp-amount);hitActor(hero);state.inv=.65;burst(hero.position,0xff866c);sound(90,.16,'sawtooth');if(state.hp<=0)finish(false)}
const upgrades=[{name:'锋芒祝福',symbol:'✦',desc:'所有武器伤害 +25%',apply:()=>state.damage+=.25},{name:'迅捷祝福',symbol:'➶',desc:'所有武器攻速 +20%',apply:()=>state.rate+=.2},{name:'急救强化',symbol:'❧',desc:'生命上限 +25，恢复 35 生命',apply:()=>{state.maxHp+=25;state.hp=Math.min(state.maxHp,state.hp+35)}},{name:'疾风靴子',symbol:'〰',desc:'移动速度 +12%',apply:()=>state.speed*=1.12},{name:'回收磁场',symbol:'◇',desc:'经验拾取范围 +2 米，恢复 15 生命',apply:()=>{state.magnet+=2;state.hp=Math.min(state.maxHp,state.hp+15)}}];
function levelUp(){state.xp=Math.max(0,state.xp-state.need);state.level++;state.need+=4;state.mode='upgrade';keys.clear();const available=COMBOS.filter(c=>!garden.combos.has(c.id)&&(c.id!=='watering'||hero.userData.rig.name==='Engineer')).map(c=>({...c,apply:()=>garden.combos.add(c.id)}));const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};const choices=available.length?[shuffle(available)[0],...shuffle([...upgrades,...available.slice(1)]).slice(0,2)]:shuffle([...upgrades]).slice(0,3);$('#modal').innerHTML=`<div class="eyebrow">FIELD MODIFICATION</div><h2>遗迹祝福</h2><p>等级 ${state.level} · 选择一种力量，继续你的旅程</p><div id="choices">${choices.map((u,i)=>`<button class="card" data-choice="${i}"><small>BLESSING / 0${i+1}</small><div class="symbol">${u.symbol}</div><h3>${u.name}</h3><p>${u.desc}</p></button>`).join('')}</div>`;$('#modal').classList.remove('hidden');document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{choices[+b.dataset.choice].apply();state.mode='playing';$('#modal').classList.add('hidden');sound(700,.2)})}
function finish(win){state.mode=win?'won':'lost';if(!win)dieActor(hero);keys.clear();best=Math.max(best,state.kills);try{localStorage.setItem('ember-best',best)}catch{}$('#modal').innerHTML=`<div class="eyebrow">${win?'ZONE SECURED':'SIGNAL LOST'}</div><h2>${win?'遗迹已守住':'行动中止'}</h2><p>${win?'你击败了骸骨巨像，遗迹工坊得以保存。':'试试不同的武器和升级组合，再来一局吧！'}</p><p>抵达第 ${state.wave} 波 · 击败 ${state.kills} · 等级 ${state.level}<br>部署 ${garden.stats.planted} 件 · 装置击杀 ${garden.stats.kills} · 伙伴 ${garden.buddies.length}<br>存活 ${Math.floor(state.time)} 秒 · 最佳 ${best} 击败</p><button id="restart" class="primary">再来一局 →</button><button id="change-hero" class="primary">更换角色</button>`;$('#modal').classList.remove('hidden');$('#restart').onclick=start;$('#change-hero').onclick=returnToTitle}
function pause(){if(!['playing','paused'].includes(state.mode))return;if(state.mode==='paused'){state.mode='playing';$('#modal').classList.add('hidden')}else{state.mode='paused';keys.clear();$('#modal').innerHTML='<div class="eyebrow">TAKE A BREATH</div><h2>休息一下</h2><p>游戏已暂停 · WASD 移动 · 空格冲刺 · 1 / 2 / 3 切换武器</p><button id="resume" class="primary">继续冒险 →</button>';$('#modal').classList.remove('hidden');$('#resume').onclick=pause}}
function dash(){if(state.mode!=='playing'||state.dash>0)return;state.dash=3;state.inv=.4;const from=hero.position.clone();hero.position.addScaledVector(lastDir,3.4);if(hero.position.length()>20)hero.position.setLength(20);garden.onDash(from,hero.position);burst(hero.position);sound(320,.15)}
$('#start').onclick=start;document.querySelectorAll('[data-character]').forEach(b=>b.onclick=()=>chooseHero(b.dataset.character));$('#pause').onclick=pause;$('#sound').onclick=()=>{muted=!muted;$('#sound').textContent=`音效 ${muted?'关':'开'}`};$('#touchdash').onclick=dash;document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);keys.add(b.dataset.key)};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key)});
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.key.toLowerCase());if(e.code==='Space')dash();if(e.key==='Escape'&&!e.repeat)pause();if(['1','2','3'].includes(e.key)&&['title','playing','paused'].includes(state.mode))equip(+e.key-1)});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();if(state.mode==='playing')pause()});
function tick(dt){if(state.mode!=='playing')return;state.time+=dt;state.waveTime+=dt;state.dash=Math.max(0,state.dash-dt);state.inv=Math.max(0,state.inv-dt);state.shot-=dt;const moveSpeed=state.speed*(hero.userData.profile.moveBonus||1),move=new T.Vector3(Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),0,Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup')));move.applyAxisAngle(new T.Vector3(0,1,0),Math.PI/4);if(move.lengthSq()){move.normalize();lastDir.copy(move);hero.position.addScaledVector(move,moveSpeed*dt);hero.rotation.y=Math.atan2(move.x,move.z);}if(combat.swing)hero.rotation.y=Math.atan2(combat.swing.dir.x,combat.swing.dir.z);animateActor(hero,dt,state.time,move.lengthSq()?moveSpeed:0);if(hero.position.length()>20)hero.position.setLength(20);hero.visible=state.inv<=0||Math.floor(state.inv*20)%2===0;
state.spawn-=dt;if(state.remaining>0&&state.spawn<=0){spawnEnemy();state.remaining--;state.spawn=Math.max(.4,1.1-state.wave*.06)}if(state.shot<=0)attack();
for(const e of enemies){if(e.dead||e.stunned)continue;e.stagger=Math.max(0,(e.stagger||0)-dt);if(e.stagger>0){animateActor(e.obj,dt,state.time,0);continue}e.slow=Math.max(0,(e.slow||0)-dt);const delta=hero.position.clone().sub(e.obj.position);const distance=delta.length();delta.normalize();if(e.type!=='spitter'||distance>8)e.obj.position.addScaledVector(delta,e.speed*(e.slow>0?.55:1)*dt);e.obj.rotation.y=Math.atan2(delta.x,delta.z);animateActor(e.obj,dt,state.time,(e.type!=='spitter'||distance>8)?e.speed*(e.slow>0?.55:1):0);e.attack-=dt;e.melee=(e.melee||0)-dt;if(distance<e.size+.45){hurt(e.type==='boss'?22:9);if(e.melee<=0){kickActor(e.obj);e.melee=.8}}if((e.type==='spitter'||e.type==='boss')&&e.attack<=0){e.attack=e.type==='boss'?2:3;const count=e.type==='boss'?10:1;for(let i=0;i<count;i++){const dir=count===1?delta.clone():new T.Vector3(Math.sin(i/count*Math.PI*2),0,Math.cos(i/count*Math.PI*2));const v=dir.multiplyScalar(5),obj=projectile(e.obj.position.clone().setY(.7),v,0,true);scene.add(obj);kickActor(e.obj);hazards.push({obj,v,life:6})}}}
enemies=enemies.filter(e=>!e.dead);combat.step(dt);
for(const h of hazards){h.life-=dt;h.obj.position.addScaledVector(h.v,dt);if(h.obj.position.distanceTo(hero.position.clone().setY(.7))<.65){hurt(12);h.life=0}}hazards=hazards.filter(h=>{if(h.life<=0){scene.remove(h.obj);return false}return true});for(const d of drops){d.obj.rotation.y+=dt*2;const delta=hero.position.clone().sub(d.obj.position).setY(0),dist=delta.length();if(dist<state.magnet)d.obj.position.addScaledVector(delta.normalize(),dt*9);if(dist<.65){if(d.heal)state.hp=Math.min(state.maxHp,state.hp+18);else state.xp+=d.value;d.dead=true;scene.remove(d.obj);sound(900,.035,'sine',.008)}}drops=drops.filter(d=>!d.dead);
if(state.mode!=='playing')return;garden.step(dt,drops,hurt);if(state.mode!=='playing')return;if(pendingElite){captureChoice();return}if(state.remaining===0&&enemies.every(e=>e.dead)){if(state.wave===8){finish(true);return}state.wave++;state.hp=Math.min(state.maxHp,state.hp+12);beginWave()}if(state.xp>=state.need)levelUp();}
function ui(){ $('#garden-counts').textContent=PLANTS.map((n,i)=>`${n} ${garden.plants.filter(p=>p.type===i&&!p.dead).length}`).join(' · ');$('#buddy-list').textContent=garden.buddies.length?'伙伴：'+garden.buddies.map(b=>`${b.type==='slime'?'采集构装体':'治愈构装体'} Lv.${b.rank}`).join(' / '):'伙伴：第 2 / 4 / 6 波精英可收服';$('#combo-list').textContent=garden.combos.size?'组合：'+COMBOS.filter(c=>garden.combos.has(c.id)).map(c=>c.name).join(' · '):'拾取战利品自动部署 · 升级解锁组合'; $('#health').style.width=`${state.hp/state.maxHp*100}%`;$('#healthtext').textContent=`${Math.ceil(state.hp)} / ${state.maxHp}`;$('#wave').textContent=String(state.wave).padStart(2,'0');$('#kills').textContent=state.kills;$('#level').textContent=state.level;$('#time').textContent=`${String(Math.floor(state.time/60)).padStart(2,'0')}:${String(Math.floor(state.time%60)).padStart(2,'0')}`;$('#xp').style.width=`${Math.min(100,state.xp/state.need*100)}%`;$('#dashstatus').textContent=state.dash>0?`冲刺冷却 ${state.dash.toFixed(1)}s`:'冲刺就绪';const boss=enemies.find(e=>e.type==='boss'&&!e.dead);$('#bossbar').classList.toggle('hidden',!boss);if(boss)$('#bossbar i').style.width=`${boss.hp/boss.maxHp*100}%`}
let last=performance.now(),uiTime=0;function frame(now){requestAnimationFrame(frame);const dt=Math.min(.04,(now-last)/1000);last=now;if(state.mode==='playing')tick(dt);if(state.mode==='lost')animateActor(hero,dt,now/1000,0);if(['playing','won','lost'].includes(state.mode)){for(const c of corpses){c.life-=dt;animateActor(c.obj,dt,now/1000,0);if(c.life<.35)c.obj.position.y-=dt*3}corpses=corpses.filter(c=>{if(c.life<=0){disposeActor(c.obj);return false}return true})}if(state.mode==='playing'||state.mode==='title'){for(const f of fx){f.life-=dt;f.obj.position.addScaledVector(f.v,dt);if(!f.fixed)f.v.y-=dt*8}fx=fx.filter(f=>{if(f.life<=0){scene.remove(f.obj);if(f.dispose){f.obj.geometry.dispose();f.obj.material.dispose()}return false}return true});flame.scale.y=.7+Math.sin(now*.006)*.15;flame.rotation.y=now*.001;toastTime-=dt;if(toastTime<=0)$('#toast').textContent=''}if(state.mode==='title'){hero.position.set(4,0,2);hero.rotation.y=now*.0003;animateActor(hero,dt,now/1000,0);camera.position.set(30,31,37);camera.lookAt(0,0,0)}else{const target=hero.position.clone().multiplyScalar(.35);camera.position.lerp(new T.Vector3(target.x+20,27,target.z+24),1-Math.exp(-dt*4));camera.lookAt(target.x,0,target.z)}uiTime+=dt;if(uiTime>.1){ui();uiTime=0}renderer.render(scene,camera)}equip();requestAnimationFrame(frame);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
// Test controls are available only with an explicit local testing query parameter.
if(new URLSearchParams(location.search).has('test'))window.__game={THREE:T,actors:Actors,state,hero,garden,get enemies(){return enemies},get drops(){return drops},get bullets(){return combat.bullets},combat,get hazards(){return hazards},get corpses(){return corpses},selectHero,chooseHero,returnToTitle,equip,attack,tick,damageEnemy,hurt,levelUp,finish,start,spawnEnemy,renderer,scene};

const guide=$('#guide');guide.onclick=()=>{if(state.mode==='playing'){pause();$('#modal').innerHTML=`<div class="eyebrow">RELIC WORKSHOP FIELD GUIDE</div><h2>把战场建成你的工坊</h2><p>① 武器击杀掉落战利品：60% 同系，其他两系各 20%　② 靠近战利品，在脚边自动部署<br>③ 装置约 1 秒启动，可存活 48 秒，最多 24 件<br>弓弩偏向自动弩台 · 霰弹偏向炼金炸瓶 · 法杖偏向雷鸣法典；每个角色都能获得三类装置<br>第 2 / 4 / 6 波的皇冠精英残血后，可选择收服或升级。<br>采集构装体收集，治愈构装体治疗充能维护；Boss 红圈践踏会破坏装置。</p><div class="guide-combos">${COMBOS.map(c=>`<div><b>${c.symbol} ${c.name}</b><p>${c.desc}</p></div>`).join('')}</div><button id="resume" class="primary">懂了，继续战斗！</button>`;$('#resume').onclick=pause}};
loadNatureAssets(scene).then(()=>{document.body.dataset.nature='loaded'}).catch(()=>{document.body.dataset.nature='fallback'});

}
boot().catch(error=>{console.error(error);const button=document.querySelector("#start");button.disabled=false;button.textContent="启动失败 · 点击重新加载";button.onclick=()=>location.reload()});
